export const CSS_COLOR_VARS = {
  accent: 'var(--color-accent)',
  accentHover: 'var(--color-accent-hover)',
  accentSoft: 'var(--color-accent-soft)',
  accentSoftAlt: 'var(--color-accent-soft-alt)',
  accentBorderSoft: 'var(--color-accent-border-soft)',
  warning: 'var(--color-warning)',
  warningStrong: 'var(--color-warning-strong)',
  warningAlt: 'var(--color-warning-alt)',
  warningSurface: 'var(--color-warning-surface)',
  warningSurfaceSoft: 'var(--color-warning-surface-soft)',
  warningBorder: 'var(--color-warning-border)',
  danger: 'var(--color-danger)',
  dangerBorderSoft: 'var(--color-danger-border-soft)',
  success: 'var(--color-success)',
  info: 'var(--color-info)',
  infoSurface: 'var(--color-info-surface)',
  textPrimary: 'var(--color-text-strong)',
  textSecondary: 'var(--color-text-secondary)',
  white: 'var(--color-white)',
};

export const COLOR_TOKENS = {
  accent: '#da1f26',
  accentHover: '#b81219',
  accentPressed: '#960f13',
  warning: '#e68619',
  warningStrong: '#b26e00',
  warningAlt: '#d17f00',
  warningChip: '#854f0b',
  warningListBorder: '#ba7517',
  warningSurface: '#fff5e6',
  warningSurfaceSoft: '#fff9e6',
  warningBorder: '#fec700',
  warningTextSoft: '#faeeda',
  info: '#1473e6',
  infoStrong: '#0c447c',
  infoListBorder: '#185fa5',
  infoSurface: '#f4f8ff',
  infoBorderSoft: '#e6f1fb',
  success: '#268e6c',
  danger: '#d7373f',
  dangerBorderSoft: 'rgba(218, 31, 38, 0.2)',
  textPrimary: '#1a1a1a',
  textSecondary: '#4b4b4b',
  textMuted: '#6e6e6e',
  white: '#fff',
  transparent: 'transparent',
  strengthWeak: '#d7373f',
  strengthFair: '#da7b11',
  strengthGood: '#b07800',
  strengthStrong: '#268e6c',
};
